[2024-04-08T13:32:51.957+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-08T13:32:34.672606+00:00 [queued]>
[2024-04-08T13:32:51.965+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-08T13:32:34.672606+00:00 [queued]>
[2024-04-08T13:32:51.965+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-08T13:32:51.988+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_tables> on 2024-04-08 13:32:34.672606+00:00
[2024-04-08T13:32:51.997+0000] {standard_task_runner.py:60} INFO - Started process 216250 to run task
[2024-04-08T13:32:52.005+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_tables', 'manual__2024-04-08T13:32:34.672606+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp0dz8bs0v']
[2024-04-08T13:32:52.009+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask create_tables
[2024-04-08T13:32:52.086+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.create_tables manual__2024-04-08T13:32:34.672606+00:00 [running]> on host 8056db226622
[2024-04-08T13:32:52.190+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T13:32:34.672606+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T13:32:34.672606+00:00'
[2024-04-08T13:32:52.206+0000] {base.py:83} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2024-04-08T13:32:52.211+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T13:32:52.222+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_tables, execution_date=20240408T133234, start_date=20240408T133251, end_date=20240408T133252
[2024-04-08T13:32:52.261+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T13:32:52.293+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
