[2024-04-08T13:36:14.310+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-08T13:36:10.857607+00:00 [queued]>
[2024-04-08T13:36:14.318+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-08T13:36:10.857607+00:00 [queued]>
[2024-04-08T13:36:14.318+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-08T13:36:14.337+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_tables> on 2024-04-08 13:36:10.857607+00:00
[2024-04-08T13:36:14.349+0000] {standard_task_runner.py:60} INFO - Started process 218052 to run task
[2024-04-08T13:36:14.355+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_tables', 'manual__2024-04-08T13:36:10.857607+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpzqn45jy6']
[2024-04-08T13:36:14.358+0000] {standard_task_runner.py:88} INFO - Job 64: Subtask create_tables
[2024-04-08T13:36:14.418+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.create_tables manual__2024-04-08T13:36:10.857607+00:00 [running]> on host 8056db226622
[2024-04-08T13:36:14.546+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T13:36:10.857607+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T13:36:10.857607+00:00'
[2024-04-08T13:36:14.567+0000] {base.py:83} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2024-04-08T13:36:14.572+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T13:36:14.584+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_tables, execution_date=20240408T133610, start_date=20240408T133614, end_date=20240408T133614
[2024-04-08T13:36:14.647+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T13:36:14.668+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
