[2024-04-08T11:06:18.276+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-08T11:06:16.046141+00:00 [queued]>
[2024-04-08T11:06:18.284+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_tables manual__2024-04-08T11:06:16.046141+00:00 [queued]>
[2024-04-08T11:06:18.285+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-08T11:06:18.304+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_tables> on 2024-04-08 11:06:16.046141+00:00
[2024-04-08T11:06:18.314+0000] {standard_task_runner.py:60} INFO - Started process 138848 to run task
[2024-04-08T11:06:18.337+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_tables', 'manual__2024-04-08T11:06:16.046141+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpecsvrztb']
[2024-04-08T11:06:18.340+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask create_tables
[2024-04-08T11:06:18.508+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.create_tables manual__2024-04-08T11:06:16.046141+00:00 [running]> on host 8056db226622
[2024-04-08T11:06:18.848+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T11:06:16.046141+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T11:06:16.046141+00:00'
[2024-04-08T11:06:18.868+0000] {base.py:83} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2024-04-08T11:06:18.895+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T11:06:18.906+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_tables, execution_date=20240408T110616, start_date=20240408T110618, end_date=20240408T110618
[2024-04-08T11:06:18.964+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T11:06:18.988+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
